# Workflow name
name: Build Slides


# Controls when the workflow will run
on: 
  # This is a reusable workflow
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:

      # In this job, all steps begin with a name
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Podman Build Book
        run: podman run --name adocpdf --rm -v $(pwd):/tmp/coursebook:Z quay.io/tmichett/asciidocpdf:latest /usr/bin/asciidoctor-revealjs Sample_Slide.adoc

      - name: Copy Slides to Index.html
        run: cp Sample_Slide.html docs/index.html

      - name: Commit and Add Book
        run: git config --global user.email "tmichett@redhat.com" && git config --global user.name "Travis Michette" && git add . && git commit -m "Added new SLIDES" && git push
